### ISSUE TITLE
Sign up form - BE

### ISSUE THREAD

**Issue by moody2times** [chingu-voyages/v40-bears-team-25#34]
**__Task Description__**
Handle the sign up request to the server

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by franceschiniandrea** [comment]
I'd say this issue is complete. We are able to handle signups and push new users to the db correctly
